import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
  const clerkJsUrl = (() => {
    if (!publishableKey) return undefined;
    const keyParts = publishableKey.split("_");
    if (keyParts.length < 3) return undefined;
    const encoded = keyParts.slice(2).join("_");
    const padded = encoded + "===".slice((encoded.length + 3) % 4);
    try {
      const decoded = Buffer.from(padded, "base64").toString("utf-8");
      const domain = decoded.replace(/\$+$/, "");
      if (!domain.includes("clerk.accounts")) return undefined;
      return `https://${domain}/npm/@clerk/clerk-js@latest/dist/clerk.browser.js`;
    } catch {
      return undefined;
    }
  })();

  return (
    <ClerkProvider
      publishableKey={publishableKey}
      clerkJSUrl={clerkJsUrl}
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignInUrl="/classes"
      afterSignUpUrl="/classes"
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
